### ISSUE TITLE
compile opencv with darknet wrong

### ISSUE THREAD

**Issue by Amerry-c** [pjreddie/darknet#691]
hi,when I compile opencv with darknet,the following error occurred:
gcc -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -DGPU -c ./src/gemm.c -o obj/gemm.o
In file included from /usr/local/include/opencv2/core/types_c.h:59:0,
                 from /usr/local/include/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv2/highgui/highgui_c.h:45,
                 from include/darknet.h:25,
                 from ./src/utils.h:5,
                 from ./src/gemm.c:2:
/usr/local/include/opencv2/core/cvdef.h:421:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^
compilation terminated due to -Wfatal-errors.
Makefile:85: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1
how can i slove it?and my opencv version is 3.3.1.thanks!

**Comment by mribbons** [comment]
What version of opencv does darknet require?

gcc --std=c++11 doesn't work because the darknet files c.

**Comment by mribbons** [comment]
I managed to get it working with opencv 3.4, locally compiled.

See gist for my Makefile and package config file:
https://gist.github.com/mribbons/2d97545dd3f678a453081a27f260b58b

**Comment by Amerry-c** [comment]
@mribbons thank you,mribbons.i  use opencv 3.4.0 to slove this problem.

**Comment by jiapei100** [comment]
Just disable OpenCV support, say: **OPENCV=0** works.
What is the relationship between OpenCV and darknet?


Cheers

**Comment by tarlen5** [comment]
Hi @Amerry-c did @mribbons fix work for you? I can't get this solution to work on my system, even though I used the opencv_darknet.pc solution that was recommended. Here is my output error:

![screen shot 2018-05-08 at 1 01 53 pm](https://user-images.githubusercontent.com/6472638/39780113-216a4c08-52c0-11e8-9653-0991a4803ad9.png)

I'm on ubuntu v16.04 with OpenCV v 3.4.1.

@mribbons any idea what's going on?

**Comment by AmmarkoV** [comment]
OpenCV is used in order to facilitate input from various data sources like webcams  ( for example ./darknet detector demo ) and in order to show visualization output windows ( i.e. https://github.com/pjreddie/darknet/blob/master/src/image.c#L575 )  
If you just want the engine and detections you don't need it ( and the fact that you can have a build with zero dependencies is the great thing about darknet ) 

Also the latest versions of OpenCV have gone full C++11 they have splitted everything in to a million sublibraries  and it is getting pretty annoying for C devs..

Things worked with OpenCV up to 3.2 so I would suggest downgrading..!  
but in any case this is not an issue of darknet but rather of openCV and its C bindings

**Comment by AlexeyAB** [comment]
This is C API bug in OpenCV 3.4.1
Darknet with OpenCV <= 3.4.0 works well.

**Comment by arjay2539** [comment]
@tarlen5 
cd ~/opencv/build (for example)

After you use command "cmake" finished, use "sudo make install".

Then, back to /darknet and use command "make".

**Comment by Amerry-c** [comment]
@tarlen5 According to https://github.com/conda-forge/opencv-feedstock, i sloved this problem

**Comment by tarlen5** [comment]
Thanks everyone for the replies. I'm still not sure what's going on, but I think the problem is related to conflicting opencv versions, since I'm also using another deep learning code base which relies on a different version of opencv, but I haven't figured out how to resolve them. As it's on AWS, I might wipe it out and start over on a new instance. The main problem is that I'm not even able to compile opencv 3.4.0 or 3.4.1, but when I finally compiled 3.3.1, I wasn't able to read in videos from .avi or .mp4 files, there were all kinds of errors :-/

If I come up with a more definite (or helpful) problem or solution, I'll reply here, but thanks again for the quick replies and suggestions, everyone.

**Comment by saktheeswaranswan** [comment]
guys i have an video tutorial on how to install opencv 3.4.0 on ubantu 18.04 and it works perfectly please go and check it it is for yolo darknet

https://www.youtube.com/watch?v=KnRJU7y5cjQ&t=197s

**Comment by spinoza1791** [comment]
Is there a workaround yet, so that we may use OpenCV 4.0.x?

**Comment by aPonza** [comment]
Check #1348

**Comment by pcgeek86** [comment]
I forked the project, incorporated a patch, and pushed it. If you use darknet from my fork, it should compile just fine. 

https://github.com/pcgeek86/darknet

**Comment by AdityaLoth** [comment]
> I forked the project, incorporated a patch, and pushed it. If you use darknet from my fork, it should compile just fine.
> 
> https://github.com/pcgeek86/darknet

Thanks for help.

**Comment by StevenOoi1996** [comment]
I forked the project, incorporated a patch, and pushed it. If you use darknet from my fork, it should compile just fine.

https://github.com/pcgeek86/darknet

Encountered: 
./darknet: error while loading shared libraries: libopencv_highgui.so.4.3: cannot open shared object file: No such file or directory

Solved:
    sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
    sudo ldconfig
    sudo apt-get install libopencv-highgui-dev

thanks to pcgeek86
