### ISSUE TITLE
yolo with cudnn

### ISSUE THREAD

**Issue by chasenzhang5** [pjreddie/darknet#2257]
I install NVIDIA drivers(version is 450.57)，CUDA11.0，cudnn8.0.1，then I modify "GPU=1 CUDNN=1" in Makefile，But when make，a error has occurred：

./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:148:5: warning: implicit declaration of function ‘cudnnGetConvolutionForwardAlgorithm’; did you mean ‘cudnnGetConvolutionForwardAlgorithm_v7’? [-Wimplicit-function-declaration]
     cudnnGetConvolutionForwardAlgorithm(cudnn_handle(),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     cudnnGetConvolutionForwardAlgorithm_v7
./src/convolutional_layer.c:153:13: error: ‘CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_FWD_ALGO_DIRECT’?
             CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             CUDNN_CONVOLUTION_FWD_ALGO_DIRECT
compilation terminated due to -Wfatal-errors.
Makefile:89: recipe for target 'obj/convolutional_layer.o' failed
make: *** [obj/convolutional_layer.o] Error 1

What could be the reason for this situation?

**Comment by RoboNuke** [comment]
I have the same issue using  NVIDIA drivers(version is 450.57)，CUDA11.0，cudnn11.0.2.39.

**Comment by chasenzhang5** [comment]
> I have the same issue using NVIDIA drivers(version is 450.57)，CUDA11.0，cudnn11.0.2.39.

I install this, then run yolov3 secceed.
nvidia-driver-440
CUDA10.2
cudnn7.6.5

**Comment by RoboNuke** [comment]
I suspected it was a version issue.  Ill give this a try tomorrow.  Thank you so much for you help!

**Comment by Michi-123** [comment]
> I install this, then run yolov3 secceed.
> nvidia-driver-440
> CUDA10.2
> cudnn7.6.5

How did you down grade from cuda11.0 to cuda10.2?
I removed cuda by bellow methods.
```
sudo apt purge cuda*
sudo apt purge nvidia-cuda-*
sudo apt purge *nvidia*
sudo apt purge libcuda*
sudo apt purge *nsight*
sudo apt-get --purge remove nvidia-*
sudo apt-get --purge remove *nvidia*
sudo apt-get --purge remove *nsight*
sudo apt-get --purge remove cuda-*
sudo apt-get --purge remove cuda
sudo apt autoremove
```
And Installed CUDA Toolkit 10.2 Download [CUDA Toolkit 10.2 Download](https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=deblocal) .

But I got this.

```
$ cat  /usr/local/cuda/version.txt
CUDA Version 11.0.228

$ ls -ld /usr/local/cuda*
lrwxrwxrwx  1 root root    9  9月 12 18:30 /usr/local/cuda -> cuda-11.0
drwxr-xr-x 15 root root 4096  9月 12 18:28 /usr/local/cuda-11.0
```

Do you have any idea? Thanks.

**Comment by Michi-123** [comment]
O-key. I did it by the method https://medium.com/@praveenkrishna/downgrade-cuda-for-tensorflow-gpu-17831db59099

It works!

**Comment by ilkin94** [comment]
> O-key. I did it by the methos at [Downgrade CUDA for Tensorflow-GPU](https://medium.com/@praveenkrishna/downgrade-cuda-for-tensorflow-gpu-17831db59099)
> 
> It works!

Thanks for the recommendation, it helped me to install clean setup. If someone has problems executing the commands in that blog, type them by hand. Sometimes characters is not recognized in terminal when copy and paste.

**Comment by Arpit599** [comment]
```
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU -DCUDNN -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:148:5: warning: implicit declaration of function ‘cudnnGetConvolutionForwardAlgorithm’; did you mean ‘cudnnGetConvolutionForwardAlgorithm_v7’? [-Wimplicit-function-declaration]
     cudnnGetConvolutionForwardAlgorithm(cudnn_handle(),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     cudnnGetConvolutionForwardAlgorithm_v7
./src/convolutional_layer.c:153:13: error: ‘CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_FWD_ALGO_DIRECT’?
             CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             CUDNN_CONVOLUTION_FWD_ALGO_DIRECT
compilation terminated due to -Wfatal-errors.
Makefile:89: recipe for target 'obj/convolutional_layer.o' failed
make: *** [obj/convolutional_layer.o] Error 1

```
I have CUDA10.2 still this issue is there, please help me solve this : (

**Comment by iAmJuan550** [comment]
Has anyone found a solution for this.

**Comment by iAmJuan550** [comment]
For those who can make this work, write your cuda and cudnn versions here

**Comment by rotrico** [comment]
Hi @priyankaakre27 
I had same issue this morning.
First I tried to build darknet with Cuda 10.2 and cudnn  8.2, getting this error.
I replaced 8.2 with 7.6 (both downloaded from nvidia web site) and I achieved to build it.

**Comment by FilippoRomeo** [comment]
I have the same problem and I am using CUDA 10.2

```
./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:148:5: warning: implicit declaration of function ‘cudnnGetConvolutionForwardAlgorithm’; did you mean ‘cudnnGetConvolutionForwardAlgorithm_v7’? [-Wimplicit-function-declaration]
     cudnnGetConvolutionForwardAlgorithm(cudnn_handle(),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     cudnnGetConvolutionForwardAlgorithm_v7
./src/convolutional_layer.c:153:13: error: ‘CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_FWD_ALGO_DIRECT’?
             CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             CUDNN_CONVOLUTION_FWD_ALGO_DIRECT
compilation terminated due to -Wfatal-errors.
Makefile:82: recipe for target 'obj/convolutional_layer.o' failed
make: *** [obj/convolutional_layer.o] Error 
```

**Comment by syanenko** [comment]
I have the same issue with CUDA 11.3, driver version: 465.19.01, RTX 2070, build with:
ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

**Comment by JinXiaozhao** [comment]
you can see the url, then run yolov3 secceed.
https://blog.csdn.net/XCCCCZ/article/details/112793411
https://github.com/arnoldfychen/darknet/blob/master/src/convolutional_layer.c

**Comment by AlfreddGco** [comment]
Isn't there any fork that makes this work with cuda 11.7 or so?

**Comment by happyamyhope** [comment]
> you can see the url, then run yolov3 secceed. https://blog.csdn.net/XCCCCZ/article/details/112793411 https://github.com/arnoldfychen/darknet/blob/master/src/convolutional_layer.c

it works for me to make.

**Comment by vineetbansal** [comment]
Just confirming that using `cuda toolkit 11.2` along with `cudnn 7.6.5` (for `cuda 10.2`) (along with a couple of minor changes to the darknet code mentioned at https://www.linuxfixes.com/2022/01/solved-does-not-name-type-when-trying.html?m=0) works.

**Comment by HHendy69** [comment]
@syanenko have you happened to find a solution? 

Ialmost have the same hardware RTX super 2070 with driver 515.65.01 and Cuda compilation tools of release 11.7 on cuda 11.7

**Comment by syanenko** [comment]
Unfortunately no (

**Comment by marv-le** [comment]
```
./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
./src/convolutional_layer.c:148:5: warning: implicit declaration of function ‘cudnnGetConvolutionForwardAlgorithm’; did you mean
 ‘cudnnGetConvolutionForwardAlgorithm_v7’? [-Wimplicit-function-declaration]
     cudnnGetConvolutionForwardAlgorithm(cudnn_handle(),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     cudnnGetConvolutionForwardAlgorithm_v7
./src/convolutional_layer.c:155:13: error: ‘CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_FWD_ALGO_DIRECT’?
             CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             CUDNN_CONVOLUTION_FWD_ALGO_DIRECT
compilation terminated due to -Wfatal-errors.
```

Had the same issue with CUDA Version: 11.7

For my case the following answer worked:
[https://forums.developer.nvidia.com/t/object-detection-on-a-webcam-with-yolo/156431/7](url)

Adding some lines to convolutional_layer.c as explained in the developer forum fixed the compatibility issue for cuDNN v8.

**Comment by Eliza-and-black** [comment]
> ```
> ./src/convolutional_layer.c: In function ‘cudnn_convolutional_setup’:
> ./src/convolutional_layer.c:148:5: warning: implicit declaration of function ‘cudnnGetConvolutionForwardAlgorithm’; did you mean
>  ‘cudnnGetConvolutionForwardAlgorithm_v7’? [-Wimplicit-function-declaration]
>      cudnnGetConvolutionForwardAlgorithm(cudnn_handle(),
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      cudnnGetConvolutionForwardAlgorithm_v7
> ./src/convolutional_layer.c:155:13: error: ‘CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT’ undeclared (first use in this function); did you mean ‘CUDNN_CONVOLUTION_FWD_ALGO_DIRECT’?
>              CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT,
>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>              CUDNN_CONVOLUTION_FWD_ALGO_DIRECT
> compilation terminated due to -Wfatal-errors.
> ```
> 
> Had the same issue with CUDA Version: 11.7
> 
> For my case the following answer worked: [https://forums.developer.nvidia.com/t/object-detection-on-a-webcam-with-yolo/156431/7](url)
> 
> Adding some lines to convolutional_layer.c as explained in the developer forum fixed the compatibility issue for cuDNN v8.

Thanks, it works for me.

**Comment by kaggar11** [comment]
> you can see the url, then run yolov3 secceed. https://blog.csdn.net/XCCCCZ/article/details/112793411 https://github.com/arnoldfychen/darknet/blob/master/src/convolutional_layer.c

Thanks, it worked for me. I was getting an error using Cuda 10.2, CuDNN 7.0. It worked with the above file changes in convolutional_layer.c with Cuda 11.2 and CuDNN 8.1.

**Comment by Aneesh02** [comment]
> you can see the url, then run yolov3 secceed. https://blog.csdn.net/XCCCCZ/article/details/112793411 https://github.com/arnoldfychen/darknet/blob/master/src/convolutional_layer.c

Yep this worked for me. CUDA 11.2 on GTX1650 CuDNN 8.0 Thanks

**Comment by crleon** [comment]
> > you can see the url, then run yolov3 secceed. https://blog.csdn.net/XCCCCZ/article/details/112793411 https://github.com/arnoldfychen/darknet/blob/master/src/convolutional_layer.c
> 
> Yep this worked for me. CUDA 11.2 on GTX1650 CuDNN 8.0 Thanks

This work for me with an GeForce RTX 4080 SUPER and CUDA 12.4
