### ISSUE TITLE
unable to locate cublas header and library for CUDA10.1

### ISSUE THREAD

**Issue by fanzeng** [pjreddie/darknet#1988]
In CUDA10.1, the headers "cublas_v2.h" and "cublas_api.h" and the library file "libcublas.so" do not exist (or do not reside where they used to be), therefore "make" would fail to compile on machines with CUDA10.1 installed.
The temporary workaround is to manually provide the headers from previous CUDA versions and symlink the libcublas.so library so it can be found. Using headers from CUDA9.0 seems to work with CUDA10.1.
For compatibility with newer version of CUDA, a check for such CUDA versions needs to be included in the Makefile and corresponding make instructions provided.

**Comment by chadwickcasp** [comment]
@fanzeng I believe I'm running into the same error as you were:

`gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU -DCUDNN -c ./src/gemm.c -o obj/gemm.o
In file included from ./src/utils.h:5:0,
                 from ./src/gemm.c:2:
include/darknet.h:13:14: fatal error: cublas_v2.h: No such file or directory
     #include "cublas_v2.h"
              ^~~~~~~~~~~~~
compilation terminated.
Makefile:91: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1
`
What symlinks should be setup for a workaround? I've already done:
`sudo ln -s /usr/local/cuda-10.1 /usr/local/cuda
sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda
`

**Comment by fanzeng** [comment]
> @fanzeng I believe I'm running into the same error as you were:
> 
> `gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU -DCUDNN -c ./src/gemm.c -o obj/gemm.o In file included from ./src/utils.h:5:0, from ./src/gemm.c:2: include/darknet.h:13:14: fatal error: cublas_v2.h: No such file or directory #include "cublas_v2.h" ^~~~~~~~~~~~~ compilation terminated. Makefile:91: recipe for target 'obj/gemm.o' failed make: *** [obj/gemm.o] Error 1 `
> 
> What symlinks should be setup for a workaround? I've already done:
> 
> `sudo ln -s /usr/local/cuda-10.1 /usr/local/cuda sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda `

I can see the main complaint from compiler is still on the non-existance of "cublas_v2.h". Can you please first try providing this header and see if it magically solves the problem? I haven't worked on darknet for a while, but I just checked what I've done at that time, apparently I copied the header from an install of CUDA9.0 and paste it in darknet/include. Please see if it works for you. If it then complains about "cublas_api.h", you may probably use the same trick. Thanks!

**Comment by chadwickcasp** [comment]
Thanks @fanzeng. I just added the cuda include paths to the makefile variables which seems to have worked.

**Comment by chadwickcasp** [comment]
Adding the necessary header paths to my PATH, and library file paths to my LD_LIBRARY_PATH works as well. This is a fix for anyone using multiple versions of CUDA (I have cublas in 10.2 and the rest of CUDA in 10.1).

**Comment by bernardoaneves** [comment]
Hi guys - I am running into the same issue:
"include/darknet.h:43:23: fatal error: cublas_v2.h: No such file or directory"

I am not particularly savvy with this. What exactly do I need to do? How do I provide the headers manually, as you say above? Thank you!

**Comment by fanzeng** [comment]
> Hi guys - I am running into the same issue:
> "include/darknet.h:43:23: fatal error: cublas_v2.h: No such file or directory"
> 
> I am not particularly savvy with this. What exactly do I need to do? How do I provide the headers manually, as you say above? Thank you!

To "provide the header manually", you can:
1. Get a copy of the missing header, in your case it's "cublas_v2.h". You may get it from other installation, copy it from your colleauge, search Github, etc. It's best if you get it from somewhere that has a similar CUDA version as yours. It's a plain text file, so it can be transferred between different computers without problems (to some extent).
2. Once you get hold onto a copy of the file "cublas_v2.h", paste it into the "include" directory of your darknet source code (or whatever folder the compiler might be searching in), make sure the pasted file name is still "cublas_v2.h".
3. Try compiling again to see if the error goes away or changes.
The above is a "dirty hack" and is probably not the best way to do it, but it's a simple way to get it going without having to acquire much "savviness".

**Comment by bernardoaneves** [comment]
> > Hi guys - I am running into the same issue:
> > "include/darknet.h:43:23: fatal error: cublas_v2.h: No such file or directory"
> > I am not particularly savvy with this. What exactly do I need to do? How do I provide the headers manually, as you say above? Thank you!
> 
> To "provide the header manually", you can:
> 
> 1. Get a copy of the missing header, in your case it's "cublas_v2.h". You may get it from other installation, copy it from your colleauge, search Github, etc. It's best if you get it from somewhere that has a similar CUDA version as yours. It's a plain text file, so it can be transferred between different computers without problems (to some extent).
> 2. Once you get hold onto a copy of the file "cublas_v2.h", paste it into the "include" directory of your darknet source code (or whatever folder the compiler might be searching in), make sure the pasted file name is still "cublas_v2.h".
> 3. Try compiling again to see if the error goes away or changes.
> 
> The above is a "dirty hack" and is probably not the best way to do it, but it's a simple way to get it going without having to acquire much "savviness".

Thank you! This seemed to work but I ended up running into other issues :(
I also had to do the same with the "cublas_api.h", by the way.

**Comment by faye-sudo** [comment]
> > > Hi guys - I am running into the same issue:
> > > "include/darknet.h:43:23: fatal error: cublas_v2.h: No such file or directory"
> > > I am not particularly savvy with this. What exactly do I need to do? How do I provide the headers manually, as you say above? Thank you!
> > 
> > 
> > To "provide the header manually", you can:
> > 
> > 1. Get a copy of the missing header, in your case it's "cublas_v2.h". You may get it from other installation, copy it from your colleauge, search Github, etc. It's best if you get it from somewhere that has a similar CUDA version as yours. It's a plain text file, so it can be transferred between different computers without problems (to some extent).
> > 2. Once you get hold onto a copy of the file "cublas_v2.h", paste it into the "include" directory of your darknet source code (or whatever folder the compiler might be searching in), make sure the pasted file name is still "cublas_v2.h".
> > 3. Try compiling again to see if the error goes away or changes.
> > 
> > The above is a "dirty hack" and is probably not the best way to do it, but it's a simple way to get it going without having to acquire much "savviness".
> 
> Thank you! This seemed to work but I ended up running into other issues :(
> I also had to do the same with the "cublas_api.h", by the way.

hey! If i have only one version for cuda,where can i get this file"cublas_v2.h"? by installing another cuda? thanks a lot !

**Comment by fanzeng** [comment]
> > > > Hi guys - I am running into the same issue:
> > > > "include/darknet.h:43:23: fatal error: cublas_v2.h: No such file or directory"
> > > > I am not particularly savvy with this. What exactly do I need to do? How do I provide the headers manually, as you say above? Thank you!
> > > 
> > > 
> > > To "provide the header manually", you can:
> > > 
> > > 1. Get a copy of the missing header, in your case it's "cublas_v2.h". You may get it from other installation, copy it from your colleauge, search Github, etc. It's best if you get it from somewhere that has a similar CUDA version as yours. It's a plain text file, so it can be transferred between different computers without problems (to some extent).
> > > 2. Once you get hold onto a copy of the file "cublas_v2.h", paste it into the "include" directory of your darknet source code (or whatever folder the compiler might be searching in), make sure the pasted file name is still "cublas_v2.h".
> > > 3. Try compiling again to see if the error goes away or changes.
> > > 
> > > The above is a "dirty hack" and is probably not the best way to do it, but it's a simple way to get it going without having to acquire much "savviness".
> > 
> > 
> > Thank you! This seemed to work but I ended up running into other issues :(
> > I also had to do the same with the "cublas_api.h", by the way.
> 
> hey! If i have only one version for cuda,where can i get this file"cublas_v2.h"? by installing another cuda? thanks a lot !

In my case, I had the previous version of cuda that has the file missing from the new version, so I copied it from there. I guess if you can't get it elsewhere (including internet), then yeah, installation another cuda that contains the file you want may be the way to go, unless you can extract the file from the installer. Do it in a virtual machine if you like.
