### PR TITLE
Make GPU option compatible with modern GCC/ CUDA by enabling -D_FORCE_INLINES for NVCC

### PR DESCRIPTION
**Pull request by jay-to-the-dee**
This fixes the compile errors that will occur when using enabling GPU acceleration on a modern (e.g. Ubuntu 15.10+) Linux installation.

### CODE REVIEW

**Comment by 2rba** [comment]
Is this a fix for errors like: 
/usr/local/cuda/include/surface_functions.h(134): error: expected a ";"

**Comment by jay-to-the-dee** [comment]
The error this fixes for me are ones like:
`/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;`

It's an error I've seen before with other CUDA projects and the `-D_FORCE_INLINES` flag to `nvcc` fixes it. It's to do with the way the source code is formatted, which is what your error sounds like too, so it sounds like it will be worth a try for you! But you'll have to confirm yourself as I haven't had the exact same error.

**Comment by masap** [comment]
Thanks ! I could build with this patch on Ubuntu 16.04.

**Comment by michaelmcmillan** [comment]
Confirming that this works for me on cuda-8.0 on Ubuntu. Also had to tweak the paths in the Makefile so that it pointed to the correct cuda version.
